### ISSUE TITLE
[BUG] colon in paper title gives error

### ISSUE THREAD

**Issue by mconley99** [alexras/libris#5]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/bottle.py", line 764, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/site-packages/bottle.py", line 1575, in wrapper
    rv = callback(*a, **ka)
  File "/Users/mconley/src/download/paper-pile/serve.py", line 35, in reload_metadata
    grab_metadata()
  File "/Users/mconley/src/download/paper-pile/serve.py", line 31, in grab_metadata
    paper_metadata[paper_name] = yaml.load(fp.read())
  File "/usr/local/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python2.7/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/local/lib/python2.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python2.7/site-packages/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/local/lib/python2.7/site-packages/yaml/scanner.py", line 580, in fetch_value
    self.get_mark())
ScannerError: mapping values are not allowed here
  in "<string>", line 1, column 12:
    title: DFTL: A Flash Translation Layer Empl ...
```

I can remove the colon in the title to make the error go away but still.

**Comment by mconley99** [comment]
It looks like I can solve this issue by simply putting the title in quotes to force yaml to parse it as a string.  For example `title: "DFTL: A Flash Translation Layer Empl... "`  I'm going to close this issue.
